name: pre-merge-actions
run-name: ${{ github.actor }} is running pre-merge tests
on: pull_request
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run:  npm
    - name: Run tests
      run: npm test