name: Automated tests
run-name: ${{ github.actor }} is running push tests
on: push
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run:  npm
    - name: Run tests
      run: npm test